apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader-worker
  namespace: youtube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reader-worker
  template:
    metadata:
      labels:
        app: reader-worker
    spec:
      containers:
        - name: reader-worker
          imagePullPolicy: Never
          image: ghcr.io/natsoman/reader-worker:local
          env:
              # How far in advance to start reading YouTube live streams. Must be between 1 minute and 1 hour (inclusive).
            - name: ADVANCE_START
              value: "15m"
              # Interval between read retry attempts. Must be between 10 seconds and 1 minute (inclusive).
            - name: RETRY_INTERVAL
              value: "10s"
            - name: YOUTUBE_GRPC_TARGET
              value: "dns:///youtube.googleapis.com:443"
            - name: ETCD_ENDPOINTS
              value: "etcd-0.etcd.etcd.svc.cluster.local:2379,etcd-1.etcd.etcd.svc.cluster.local:2379,etcd-2.etcd.etcd.svc.cluster.local:2379"
          envFrom:
            - configMapRef:
                name: common
            - secretRef:
                name: common
            - secretRef:
                name: worker
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
